### ISSUE TITLE
Combat state not properly tracked

### ISSUE THREAD

**Issue by somebears** [Twinkiee/TwinkiePlates#2]
Twinkieplates seem to have carried over a bug from the NPrime nameplates.

Whenever I use Voidslip, the Plates show the out of combat configuration. I hide most stuff in combat (such as cast bars).

Void slip does not seem to be the only thing triggering this.(can't reproduce it :/)

Also in NPrime plates, there was an Issue with the avatus fight. Whenever you were teleported into another room, the same thing happened (probably because on a zone change) I will test the Avatus part tonight

**Comment by Twinkiee** [comment]
Hi Somebears,
thank you for your reporting.

While I reworked some aspects of the "in-combat" state detection, TwinkiePlates still relies on the UnitEnteredCombat event and determines its in/out of combat settings upon the value returned by that event.
This means that:
1) Void Slip will put you out of combat until you don't engage another unit and/or exit from the Void
2) It may not update the nameplate layout for those units that triggered their UnitEnteredCombat event more than 130m away from the player

I'm trying to add some additional "in-combat" detection settings that are supposed to be less error-prone than the one currently in place and also add some additional checks that should help mitigate the aforementioned issues.
I still need to deeply test them thou.

Regards,
Twinkie

**Comment by somebears** [comment]
Hey, sorry for the late reply.

The thing is that void slip does not put you out of combat in instanced content. As long as someone in your group is still in combat, so are you.

I've been looking over the lua code a bit and it seems to me like combat state is checked for each unit individually. 

So when exiting the void, the other players appear again, but they do not enter combat (because they are already in combat). That seems to lead to the fact that their combat state is tracked wrong.

Wouldn't it be easier to make the combat state depending only on your own state? This way would probably be a bit faster, because combat state does not need to be updated and stored on a general unit level, but instead only for one unit (the player)

However, I am no lua expert (as in never written anything ever), so all of this might be wrong

**Comment by Twinkiee** [comment]
You're right, combat state is tracked individually.
I have to double check the Void Slip behavior but I'm still quite confident that the root cause of the issue is that the UnitEnteredCombat event, even if it's supposed to be the most efficient way tho halde this kind of stuff, is not a reliable way to track the actual unit's combat state.

I'm also adding an option to determine the combat state upon the player's character state but I want to keep it as an optional setting (maybe even the default one).

I'll have some more updates in the near future.

**Comment by somebears** [comment]
If I remember correctly, RaidCore uses a "IsInCombat()" call, to determine combat state at some points.

Maybe the solution would be to check that state when new nameplates are created/unhidden. That would preserve the current functionality and have a rather low performance impact

**Comment by Twinkiee** [comment]
Yes, the IsInCombat API is definitely going to be required. ~~Hopefully the combat state is already available when the unit (and thus the nameplate) is created.~~
The IsInCombat is already in place and currently doesn't seem to properly work.

I'll update as soon as possible. Changed the bug title accordingly.

**Comment by Twinkiee** [comment]
Combat state detection changed.
Still missing "personal combat state" mode feature.
