### ISSUE TITLE
Despite the update, the nameplates are not showing.

### ISSUE THREAD

**Issue by Datachange** [Twinkiee/TwinkiePlates#5]
Title explains it all.

**Comment by Twinkiee** [comment]
Yes, for some reason Curse it's publishing an older realease (1.4.9) instead of the latest one.
I did another tag, hopefully this is going to be the right one.

Let me know how it goes.
Twinkie.

**Comment by Datachange** [comment]
I did the manual fix found on https://www.reddit.com/r/WildStar/comments/54xggj/how_to_fix_addons/

However, I see the new install from Curse and did a reinstall (forced update) to hopefully undo my manual fix. Things seem to be in working order, now. Thank you.
